In [2]:
if 1==1 and 2==2 and 3==3: print ("(ok)")

(ok)


In [3]:
x = 1 if 1+1==1 else 2
print (x)

2


In [5]:
import pandas as pd

In [6]:
d = {'a':[1,2,3,4,5,6], 'b':[1,2,3,4,5,6]}
df = pd.DataFrame(d)
bad_df = df.index.isin([3,5])

In [7]:
bad_df

array([False, False, False,  True, False,  True], dtype=bool)

In [9]:
df

a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
5  6  6

In [10]:
df[~bad_df]

a  b
0  1  1
1  2  2
2  3  3
4  5  5

In [11]:
df.drop([0,1])

a  b
2  3  3
3  4  4
4  5  5
5  6  6

In [12]:
df

a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
5  6  6

In [13]:
import numpy as np
np.random.random_integers(5, size=(3))

C:\Users\chuco\Anaconda3\envs\bunny_theano\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  


array([1, 1, 4])

In [18]:
x = np.array([1,2,3,4,5,6,7,8,89,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8, 89, 10])

In [20]:
idx = np.array([1,2,3,2,1])

In [21]:
x[idx]

array([2, 3, 4, 3, 2])

In [28]:
np.choose(x,np.array([1,  0,  1,  1,  1,  0,  1,  0, 1, 0]).T)

ValueError: invalid entry in choice array